server.port=8080

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/today_departure?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=aisw
spring.datasource.password=aisw

mybatis.mapper-locations=classpath:/mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
spring.sql.init.continue-on-error=false
spring.sql.init.encoding=UTF-8

# 공공 API 키 설정
api.service-key=2dc8847e3d266a050537367834b26158359b1f24b1b1fda048fe7f2424e6327

# ODsay API Key 설정 (추가)
odsay.api.key=VuH9fmjFMsn0k5jpBaSn6g

# TMAP 지도/POI/대중교통 API
tmap.api.key=M3NNT78vK82uK7Mekk3hF3b1rfeZ1TZIaOVS9JGX
