spring.application.name=springProject

# MySQL 연결
spring.datasource.url=jdbc:mysql://localhost:3306/today_departure?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=aisw
spring.datasource.password=aisw
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

logging.level.web=DEBUG

# 포트 (기본 8080)
server.port=8080